version: '3'

services:
  redis:
    image: "redis/redis-stack-server:latest"

  mainapp:
    build: .
    depends_on:
      - "redis"
    ports:
      - 8000:8000

    links:
      - "redis:redis"
    environment:
      - "REDIS_HOST=${REDIS_HOST:-redis}"
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure
