version: '3'

services:
  redis:
    image: "redis/redis-stack-server:latest"

  backend:
    build: .
    depends_on:
      - "redis"

    links:
      - "redis:redis"
    environment:
      - "REDIS_HOST=${REDIS_HOST:-redis}"
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure

  frontend:
    build: ./frontend
    depends_on:
      - "backend"
    links:
      - "backend:backend"
    ports:
      - 8000:80